/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router on build.
// A minimal stub is committed so the project typechecks before first generate.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiPublicCampaignBriefRouteImport } from "./routes/api/public/campaign-brief";
import { Route as ApiPublicTelegramWebhookRouteImport } from "./routes/api/public/telegram-webhook";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

const ApiPublicCampaignBriefRoute = ApiPublicCampaignBriefRouteImport.update({
  id: "/api/public/campaign-brief",
  path: "/api/public/campaign-brief",
  getParentRoute: () => rootRouteImport,
} as any);

const ApiPublicTelegramWebhookRoute = ApiPublicTelegramWebhookRouteImport.update({
  id: "/api/public/telegram-webhook",
  path: "/api/public/telegram-webhook",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/public/campaign-brief": typeof ApiPublicCampaignBriefRoute;
  "/api/public/telegram-webhook": typeof ApiPublicTelegramWebhookRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/public/campaign-brief": typeof ApiPublicCampaignBriefRoute;
  "/api/public/telegram-webhook": typeof ApiPublicTelegramWebhookRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/public/campaign-brief": typeof ApiPublicCampaignBriefRoute;
  "/api/public/telegram-webhook": typeof ApiPublicTelegramWebhookRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/api/public/campaign-brief" | "/api/public/telegram-webhook";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/api/public/campaign-brief" | "/api/public/telegram-webhook";
  id: "__root__" | "/" | "/api/public/campaign-brief" | "/api/public/telegram-webhook";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiPublicCampaignBriefRoute: typeof ApiPublicCampaignBriefRoute;
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/public/campaign-brief": {
      id: "/api/public/campaign-brief";
      path: "/api/public/campaign-brief";
      fullPath: "/api/public/campaign-brief";
      preLoaderRoute: typeof ApiPublicCampaignBriefRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/public/telegram-webhook": {
      id: "/api/public/telegram-webhook";
      path: "/api/public/telegram-webhook";
      fullPath: "/api/public/telegram-webhook";
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCampaignBriefRoute: ApiPublicCampaignBriefRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
